config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :posts
  resources :follows

  post ':id/follow_user', to: 'follows#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'follows#unfollow_user', as: :unfollow_user

  post ':id/like_post', to: 'posts#like_post', as: :like_post
  post ':id/unlike_post', to: 'posts#unlike_post', as: :unlike_post

  resources :post_comments, :except => [:index, :edit, :update, :show] do
    collection do
      get 'new/:post_id', :to => "post_comments#new", :as => 'new'
    end
  end

  get 'explore/posts', to: 'posts#explore', as: :posts_explore
  get 'profiles/:id', to: 'profile#show', as: :profile
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  default_scope { order(created_at: :desc) }

  belongs_to :post
  belongs_to :user

  validates_presence_of :comment, :post_id, :user_id
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :set_post_comment, only: [:destroy]

  # GET /post_comments/new
  def new
    @post_comment = PostComment.new
    @post_comment.post_id = params[:post_id]
  end

  # POST /post_comments
  # POST /post_comments.json
  def create
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.user_id = current_user.id

    respond_to do |format|
      if @post_comment.save
        format.html { redirect_to :back, notice: 'Post comment was successfully created.' }
        format.json { render :show, status: :created, location: @post_comment }
      else
        format.html { render :new }
        format.json { render json: @post_comment.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  # DELETE /post_comments/1
  # DELETE /post_comments/1.json
  def destroy
    @post_comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Post comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_comment
      @post_comment = PostComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_comment_params
      params.require(:post_comment).permit(:post_id, :user_id, :comment)
    end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_form.html.erb
<%= form_for(post_comment, remote: true) do |f| %>
  <% if post_comment.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% post_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :post_id %>
  </div>
  <div class="field">
    <%= f.text_field :comment, class: 'form-control' %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit 'Add comment', class: 'btn btn-primary '%>
  </div>
<% end %>

app/views/post_comments/_new.html.erb
<div class="row">
  <div class="col-md-9 col-xs-9">
    <h4>Add a comment</h4>
  </div>
  <div class="col-md-3 col-xs-3 text-right">
    <span class="close" data-dismiss="modal" aria-label="Close">×</span>
  </div>
</div>
<%= render 'form', post_comment: post_comment%>

app/views/post_comments/new.html.erb
<h1>New Post Comment</h1>

<%= render 'form', post_comment: @post_comment %>

<%= link_to 'Back', post_comments_path %>

app/views/post_comments/new.js.erb
$('#comment_form_container').html("<%= j render('new',post_comment: @post_comment) %>");