config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :posts
  resources :follows

  post ':id/follow_user', to: 'follows#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'follows#unfollow_user', as: :unfollow_user

  post ':id/like_post', to: 'posts#like_post', as: :like_post
  post ':id/unlike_post', to: 'posts#unlike_post', as: :unlike_post

  resources :post_comments, :except => [:index, :edit, :update, :show] do
    collection do
      get 'new/:post_id', :to => "post_comments#new", :as => 'new'
    end
  end

  get 'explore/posts', to: 'posts#explore', as: :posts_explore
  get 'profiles/:id', to: 'profile#show', as: :profile
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: 'User'
  belongs_to :following, foreign_key: :following_id, class_name: 'User'
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_user, only: [:follow_user, :unfollow_user]
  def index
    @users = User.all
  end

  def follow_user
    if current_user.follow @user.id
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unfollow_user
    if current_user.unfollow @user.id
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/follows/index.html.erb
<div class="container bootstrap snippet">
  <div class="row">
    <div class="col-lg-12">
      <div class="main-box no-header clearfix">
        <div class="main-box-body clearfix">
          <div class="table-responsive">
            <table class="table user-list">
              <thead>
              <tr>
                <th><span>User</span></th>
                <th><span>Email</span></th>
                <th><span>Created</span></th>
                <th><span>Following</span></th>
                <th><span>Followers</span></th>
                <th>&nbsp;</th>
              </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                  <tr>
                    <td>
                      <img src="<%= user.user_picture %>" alt="" style="width:10%">
                      <%= link_to user.username, profile_path(user.id), class: 'user-link' %>
                    </td>
                    <td>
                      <a href="#"><%= user.email %></a>
                    </td>
                    <td><%= user.created_at %></td>
                    <td><%= user.following.size %></td>
                    <td><%= user.followers.size %></td>
                    <td style="width: 20%;">
                      <% if user == current_user %>
                          <%=  link_to 'Your Profile', profile_path(user),
                                       class: 'btn btn-default'  %>
                      <% else %>
                          <% if current_user_is_following(current_user.id, user.id) %>
                              <%= link_to 'Unfollow', unfollow_user_path(user),
                                          class: 'btn btn-danger',
                                          id: 'unfollow-button',
                                          method: :post %>
                          <% else %>
                              <%= link_to 'Follow', follow_user_path(user),
                                          class: 'btn btn-primary',
                                          id: 'follow-button',
                                          method: :post %>
                          <% end %>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>