config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :posts
  resources :follows

  post ':id/follow_user', to: 'follows#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'follows#unfollow_user', as: :unfollow_user

  post ':id/like_post', to: 'posts#like_post', as: :like_post
  post ':id/unlike_post', to: 'posts#unlike_post', as: :unlike_post

  resources :post_comments, :except => [:index, :edit, :update, :show] do
    collection do
      get 'new/:post_id', :to => "post_comments#new", :as => 'new'
    end
  end

  get 'explore/posts', to: 'posts#explore', as: :posts_explore
  get 'profiles/:id', to: 'profile#show', as: :profile
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :description

    belongs_to :user
    has_many :post_likes
    has_many :post_comments

    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

    validates :description, format: {with: /(?=.*[a-zA-Z0-9])(?=.*(#)).+/, message: 'must contain at least one hashtag'}
    validates_attachment :image, presence: true,
                         content_type: { content_type:
                                             [
                                                 'image/tiff',
                                                 'image/tif',
                                                 'image/png',
                                                 'image/jpeg',
                                                 'image/jpg'
                                             ]
                         }

    scope :not_mine, ->(user_id) {
      where.not(user_id: user_id)
    }

    def like(user_id)
      post_likes.create(user_id: user_id)
    end

    def unlike(user_id)
      post_likes.find_by(user_id: user_id).destroy
    end

    def get_likes_list
      string = ""
      post_likes.each do |like|
        string += like.user.username + ", "
      end
      string.chomp(', ') + " like this picture"
    end

    def self.popular
      popular_hash = Hash.new
      Post.all.each do |post|
        total_value = post.post_comments.size + (0.5 * post.post_likes.size)
        popular_hash[post.id] = total_value
      end

      ids = popular_hash.sort_by { |key, value| value }.reverse.map{|key,value| key}

      Post.find(ids).sort_by {|m| ids.index(m.id)}
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like_post, :unlike_post]

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.timeline
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to profile_path(current_user), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_post
    if @post.like(current_user.id)
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlike_post
    if @post.unlike(current_user.id)
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def explore
    if params.key?(:q)
      @posts = Post.not_mine(current_user.id).where("description LIKE ?", "%#{params[:q]}%")
    else
      @posts = Post.not_mine(current_user.id).order("RANDOM()")
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def current_user_has_liked(current_user_id, post_id)
    relationship = PostLike.find_by(user_id: current_user_id, post_id: post_id)
    return true if relationship
  end
end

app/views/posts/_form.html.erb
<%= form_for post, html: { multipart: true } do |f| %>
    <% if post.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <br/>
    <div class="actions">
      <%= f.submit 'Create post', class: 'form-control btn btn-primary' %>
    </div>
<% end %>

app/views/posts/_list.html.erb
<% if @posts.size.to_i > 0 %>
    <% @posts.each do |post| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <a class="lightbox" href="<%= post_path(post) %>">
              <%= image_tag post.image.url(:medium) %>
            </a>
            <div class="caption">
              <h3>
                <%= post.description %>
                <% if current_user_has_liked(current_user.id, post.id) %>
                    <%= link_to unlike_post_path(post), method: :post do %>
                        <i class="fa fa-heart red-symbol"></i></a>
                    <% end %>
                <% else %>
                    <%= link_to like_post_path(post), method: :post do %>
                        <i class="fa fa-heart-o grey-symbol"></i></a>
                    <% end %>
                <% end %>
                <%= link_to new_post_comments_path(post.id), data: {toggle: 'modal', target: '#comment_picture', id: post.id}, remote: true do %>
                    <i class="fa fa-comment-o"></i>
                <% end %>
              </h3>
              <p><%= pluralize(post.post_likes.size, 'like') + ' - ' + pluralize(post.post_comments.size, 'comment') %></p>
              <p>Uploaded <%= time_ago_in_words(post.created_at) %> ago by: <%= link_to post.user.username, profile_path(post.user) %></p>
            </div>
          </div>
        </div>
    <% end %>
<% else %>
    <h1>No photos to show!</h1>
<% end %>

app/views/posts/_new.html.erb
<div class="row">
  <div class="col-md-9 col-xs-9">
    <h4>Add a new post</h4>
  </div>
  <div class="col-md-3 col-xs-3 text-right">
    <span class="close" data-dismiss="modal" aria-label="Close">×</span>
  </div>
</div>
<%= render 'form', post: post %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/explore.html.erb
<div class="container gallery-container">

  <h1>Explore photos</h1>

  <p class="page-description text-center">The list of photos</p>

  <div class="tz-gallery">
    <div class="row">
      <%= form_tag('/explore/posts', method: 'get') do %>
          <div class="col-lg-3" style="float:right; margin-bottom: 15px; margin-right: 15px;">
            <div class="input-group">

              <input type="text" class="form-control" name="q" placeholder="Search for..." value="<%= params[:q] %>">
              <span class="input-group-btn">
                <%= submit_tag 'Search', class: 'btn btn-secondary' %>
          </span>
            </div>
          </div>
      <% end %>
    </div>
    <div class="row">
      <%= render 'list' %>
    </div>

  </div>

</div>
<div class="modal fade" id="comment_picture" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div id="comment_form_container">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container gallery-container">

  <h1>Timeline</h1>

  <p class="page-description text-center">The list of images</p>

  <div class="tz-gallery">

    <div class="row">
      <%= render 'list' %>

    </div>

  </div>

</div>
<div class="modal fade" id="comment_picture" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div id="comment_form_container">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-6">
  <h1>New Post</h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/new.js.erb
$('#post_form_container').html("<%= j render('new',post: @post) %>");

app/views/posts/show.html.erb
<div class="row">
  <div class="center-block" style="width:700px; ">
    <h3><%= @post.description %></h3>
    <%= image_tag @post.image, style: 'max-width: 700px' %>
    <p><%= @post.get_likes_list %></p>
  </div>
  <div class="center-block" style="width:700px; margin-top: 25px">
    <section class="comments">
      <% @post.post_comments.each do |comment| %>
      <article class="comment">
        <a class="comment-img" href="#non">
          <%= image_tag comment.user.user_picture %>
          </a>
        <div class="comment-body">
          <div class="text">
            <p><%= comment.comment %></p>
          </div>

            <p class="attribution">by <a href="#non"><%= comment.user.username %></a> <%= time_ago_in_words(comment.created_at) %> ago
              <% if comment.user_id == current_user.id %>
                <%= link_to '<i class="fa fa-trash"></i>'.html_safe, comment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'right' %>
              <% end %>
            </p>
        </div>
      </article>
      <% end %>
    </section>
  </div>
</div>