config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :posts
  resources :follows

  post ':id/follow_user', to: 'follows#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'follows#unfollow_user', as: :unfollow_user

  post ':id/like_post', to: 'posts#like_post', as: :like_post
  post ':id/unlike_post', to: 'posts#unlike_post', as: :unlike_post

  resources :post_comments, :except => [:index, :edit, :update, :show] do
    collection do
      get 'new/:post_id', :to => "post_comments#new", :as => 'new'
    end
  end

  get 'explore/posts', to: 'posts#explore', as: :posts_explore
  get 'profiles/:id', to: 'profile#show', as: :profile
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Povio Test</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Povio Test</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Timeline', posts_path, class: current_class?(posts_path) %></li>
          <li><%= link_to 'Explore', posts_explore_path, class:  current_class?(posts_path) %></li>
          <li><%= link_to 'People', follows_path, class:  current_class?(follows_path) %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to current_user.username, profile_path(current_user) %>
          </li>
          <li>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
    <%= yield %>
  </body>
</html>
<div class="modal fade" id="comment_picture" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div id="comment_form_container">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Povio Test</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
</head>

<body>
<div class="container">


  <div class="omb_login">
    <h3 class="omb_authTitle"><%= link_to 'Login', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %></h3>
    <div class="row omb_row-sm-offset-3 omb_socialButtons">
      <div class="col-xs-12 col-sm-6">
        <%= link_to user_facebook_omniauth_authorize_path, class: 'btn btn-lg btn-block omb_btn-facebook' do %>
          <i class="fa fa-facebook visible-xs"></i>
          <span class="hidden-xs">Facebook</span>
        <% end %>
      </div>
    </div>

    <div class="row omb_row-sm-offset-3 omb_loginOr">
      <div class="col-xs-12 col-sm-6">
        <hr class="omb_hrOr">
        <span class="omb_spanOr">or</span>
      </div>
    </div>

    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>